### src/config/simclr.yaml
defaults:
  - engine: simclr
  - dataset: web
  - model : resnet

name : "simclr"
pretrained_model_point : ""
last_engine_checkpoint : ""
resolution : 224
n_views : 2
epochs : 10
lr : 0.0003
weight_decay : 1e-4
log_every_n_steps : 10
precision : 16
temperature : 0.07
fp16_precision : True
num_workers : 4
time_per_epoch : 0.25
engine_checkpoints : "engine_checkpoints"
model_checkpoints : "model_checkpoints"