### src/config/supr.yaml
defaults:
  - engine: supr
  - dataset: trusted
  - model : resnet

pretrained_point : "checkpoints/simclr-epoch=3-train_loss=1.57-train_acc_top1=0.00.ckpt"
last_checkpoint : ""
resolution : 224
n_views : 2
epochs : 10
lr : 0.0003
weight_decay : 1e-4
log_every_n_steps : 10
precision : 16
temperature : 0.07
fp16_precision : True
num_workers : 4
time_per_epoch : 0.25
checkpoints : "checkpoints"