### src/config/supr_hresnet.yaml
defaults:
  - _self_
  - engine: supr
  - dataset: trusted
  - model : hresnet

batch_size : 32
name : "supr_hresnet"
pretrained_model : False
pretrained_model_point : ""
last_engine_checkpoint : ""
resolution : 224
n_views : 2
epochs : 10
optimizer: "Adam"
scheduler: "CosineAnnealingLR"
lr : 0.0003
momentum : 0.9
weight_decay : 1e-4
log_every_n_steps : 10
precision : bf16
temperature : 0.07
fp16_precision : True
num_workers : 3
time_per_epoch : 0.25
engine_checkpoints : "engine_checkpoints"
model_checkpoints : "model_checkpoints"