### src/config/supr_hcct_14_7x2_224.yaml
defaults:
  - _self_
  - engine: supr
  - dataset: trusted
  - model : hcct_14_7x2_224

batch_size : 32
name : "supr_hcct_14_7x2_224"
pretrained_model : True
pretrained_model_point : ""
last_engine_checkpoint : ""
resolution : 224
n_views : 2
epochs : 10
optimizer: "LAMB"
scheduler: "CosineAnnealingLR"
lr : 0.0003
momentum : 0.9
weight_decay : 0.05
log_every_n_steps : 10
precision : 16
temperature : 0.07
fp16_precision : True
num_workers : 2
time_per_epoch : 0.25
engine_checkpoints : "engine_checkpoints"
model_checkpoints : "model_checkpoints"