### src/config/supr_resnet.yaml
defaults:
  - engine: supr
  - dataset: trusted
  - model : resnet

batch_size : 56
name : "supr"
pretrained_model_point : "engine=simclr-model=resnet-epoch=8-train_loss=4.10-train_acc=0.17--val_loss=0.00-val_acc=0.00.ckpt"
last_engine_checkpoint : ""
resolution : 224
n_views : 2
epochs : 10
lr : 0.0003
momentum : 0.9
weight_decay : 1e-4
log_every_n_steps : 10
precision : 16
temperature : 0.07
fp16_precision : True
num_workers : 4
time_per_epoch : 0.25
engine_checkpoints : "engine_checkpoints"
model_checkpoints : "model_checkpoints"