defaults:
  - _self_
  - engine: supr
  - dataset: fungi
  - model : htimm_model

batch_size : 176 #80 #176
name : "supr_htimm"
pretrained_version : vit_base_patch16_224 #"convnext_base_in22ft1k" # "vit_base_patch16_224" 
pretrained_model : True
pretrained_model_point : ""
last_engine_checkpoint : 
  engine : supr
  path : ""
resolution : 224
resolution_test : 224 #288
n_views : 2
epochs : 20
optimizer: "Adam"
scheduler: "StepLR"
lr : 0.0001
momentum : 0.9
weight_decay : 1e-4
log_every_n_steps : 10
precision : 16
temperature : 1.0
fp16_precision : True
num_workers : 6
time_per_epoch : 0.25
engine_checkpoints : "engine_checkpoints"
model_checkpoints : "model_checkpoints"
